name: Deployment

on:
    push:
        tags:
            - 'v*'

defaults:
    run:
        shell: bash

jobs:
    linux:
        name: Linux
        runs-on: ubuntu-20.04
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: Fetch tag git metadata
                run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
            -   name: Check for .NET 6 preinstalled
                id: dotnet_check
                run: |
                    compgen -G "~/.dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || \
                    compgen -G "/usr/local/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || \
                    compgen -G "/usr/share/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || true
            -   uses: actions/setup-dotnet@v1.9.1
                if: ${{ steps.dotnet_check.outputs.has_6_0 != 'true' }}
                with:
                    dotnet-version: 6.0.x
            -   name: NuGet Auth
                uses: StirlingLabs/GithubNugetAuthAction@main
            -   name: Build
                run: dotnet build StirlingLabs.MsQuic.sln -c Release
            -   name: Test
                run: dotnet test StirlingLabs.MsQuic.sln --no-build -c Release --logger GitHubActions
            -   name: Artifacts
                uses: actions/upload-artifact@v2
                with:
                    name: Utilities.Net
                    path: |
                        artifacts/*.nupkg
                    if-no-files-found: error
            -   name: Push NuGet Packages
                run: dotnet nuget push artifacts/*.nupkg -k ${{github.token}} -s https://nuget.pkg.github.com/${{github.repository_owner}}/index.json -n 1 || true
            -   name: Save coverage to storage branch
                uses: StirlingLabs/BranchStorageAction@v21.07.3
                with:
                    comment: |
                        Coverage for ${{github.ref}}
                        Action: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
                        Commit: https://github.com/${{github.repository}}/commit/${{github.sha}}
                    storage-branch: coverage
                    src: coverage
                    dst: coverage
                    prune: true
    
    macos:
        name: Mac
        runs-on: macos-11
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: Fetch tag git metadata
                run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
            -   name: Check for .NET 6 preinstalled
                id: dotnet_check
                run: |
                    compgen -G "~/.dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || \
                    compgen -G "/usr/local/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || \
                    compgen -G "/usr/share/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || true
            -   uses: actions/setup-dotnet@v1.9.1
                if: ${{ steps.dotnet_check.outputs.has_6_0 != 'true' }}
                with:
                    dotnet-version: 6.0.x
            -   name: NuGet Auth
                uses: StirlingLabs/GithubNugetAuthAction@main
            -   name: Test
                run: dotnet test StirlingLabs.MsQuic.sln -c Release --logger GitHubActions


    windows:
        name: Windows
        runs-on: windows-2022
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: Fetch tag git metadata
                run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
            -   name: Check for .NET 6 preinstalled
                id: dotnet_check
                run: |
                    compgen -G "/C/Program Files/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true"
            -   uses: actions/setup-dotnet@v1.9.1
                if: ${{ steps.dotnet_check.outputs.has_6_0 != 'true' }}
                with:
                    dotnet-version: 6.0.x
            -   name: NuGet Auth
                uses: StirlingLabs/GithubNugetAuthAction@main
            -   name: Test
                run: dotnet test StirlingLabs.MsQuic.sln -c Release --logger GitHubActions

    create_release:
        name: Create Release
        runs-on: ubuntu-20.04
        needs: [ linux, macos, windows ]
        steps:
            -   uses: actions/download-artifact@v2
                with:
                    path: artifacts
            -   name: Create Release
                uses: softprops/action-gh-release@v0.1.12
                with:
                    name: StirlingLabs.MsQuic
                    files: |
                        artifacts/**
