name: Integration
on:
    push:
        branches:
            - main
    workflow_dispatch:

defaults:
    run:
        shell: bash

jobs:

    skip_check:
        name: Skip Run Check
        continue-on-error: true
        runs-on: ubuntu-20.04
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
            is_not_release: ${{ steps.release_check.outputs.is_not_release }}
        steps:
            -   name: Check if duplicate action
                id: skip_check
                uses: fkirc/skip-duplicate-actions@master
                with:
                    skip_after_successful_duplicate: 'true'
                    paths_ignore: '["**/README.md", ".idea/**", ".editorconfig", ".git*", "docs/**", ".github/**"]'
            -   name: Full checkout
                if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Check if should be release / has version tag
                id: release_check
                if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
                run: |
                    git describe --exact-match --match='v*' --abbrev=0 --tags ${{ github.sha }} 2>/dev/null \
                    || echo "::set-output name=is_not_release::true"

    linux:
        name: Linux
        needs: skip_check
        if: ${{ (needs.skip_check.outputs.should_skip != 'true') && (needs.skip_check.outputs.is_not_release == 'true') }}
        runs-on: ubuntu-20.04
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: Fetch tag git metadata
                run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
            -   name: Check for .NET 6 preinstalled
                id: dotnet_check
                run: |
                    compgen -G "~/.dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || \
                    compgen -G "/usr/local/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || \
                    compgen -G "/usr/share/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || true
            -   uses: actions/setup-dotnet@v1.9.1
                if: ${{ steps.dotnet_check.outputs.has_6_0 != 'true' }}
                with:
                    dotnet-version: 6.0.x
            -   name: NuGet Auth
                uses: StirlingLabs/GithubNugetAuthAction@main
            -   name: Build
                run: dotnet build StirlingLabs.MsQuic.sln -c Release
            -   name: Test
                run: dotnet test StirlingLabs.MsQuic.sln --no-build -c Release --logger GitHubActions
            -   name: Artifacts
                uses: actions/upload-artifact@v2
                with:
                    name: Utilities.Net
                    path: |
                        artifacts/*.nupkg
                    if-no-files-found: error

    macos:
        name: Mac
        needs: skip_check
        if: ${{ (needs.skip_check.outputs.should_skip != 'true') && (needs.skip_check.outputs.is_not_release == 'true') }}
        runs-on: macos-12
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: Fetch tag git metadata
                run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
            -   name: Check for .NET 6 preinstalled
                id: dotnet_check
                run: |
                    compgen -G "~/.dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || \
                    compgen -G "/usr/local/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || \
                    compgen -G "/usr/share/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true" || true
            -   uses: actions/setup-dotnet@v1.9.1
                if: ${{ steps.dotnet_check.outputs.has_6_0 != 'true' }}
                with:
                    dotnet-version: 6.0.x
            -   name: NuGet Auth
                uses: StirlingLabs/GithubNugetAuthAction@main
            -   name: Test
                run: dotnet test StirlingLabs.MsQuic.sln -c Release --logger GitHubActions


    windows:
        name: Windows
        needs: skip_check
        if: ${{ (needs.skip_check.outputs.should_skip != 'true') && (needs.skip_check.outputs.is_not_release == 'true') }}
        runs-on: windows-2022
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
            NUGET_CERT_REVOCATION_MODE: offline
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: Fetch tag git metadata
                run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
            -   name: Check for .NET 6 preinstalled
                id: dotnet_check
                run: |
                    compgen -G "/C/Program Files/dotnet/sdk/6.0.*" \
                    && echo "::set-output name=has_6_0::true"
            -   uses: actions/setup-dotnet@v1.9.1
                if: ${{ steps.dotnet_check.outputs.has_6_0 != 'true' }}
                with:
                    dotnet-version: 6.0.x
            -   name: NuGet Auth
                uses: StirlingLabs/GithubNugetAuthAction@main
            -   name: Test
                run: dotnet test StirlingLabs.MsQuic.sln -c Release --logger GitHubActions

